import os

########## TELEGRAM SETTINGS #############
API_TOKEN = os.environ["API_TOKEN_MOZART"]
GROUP_CHAT_ID = int(os.environ["GROUP_CHAT_ID_COTTAGE"])
WEBHOOK_URL_BASE = os.environ["WEBHOOK_URL_BASE"]
WEBHOOK_URL_PATH = "/%s/" % (API_TOKEN)

########## APP SETTINGS #############
LINE_UPPER_TANK = 26
LINE_UPPER_TANK_AV = 17
LINE_HEAT_SENSOR = 11
LINE_HEAT_HUN_SENSOR = 10

RAIN_HOURS = 12
RAIN_MAX = 1500  # mm per m^2
RAIN_CONSTANT_VOLUME = 0.73  # 8.2  ml per 120cm^2 -- 0.069 mm per m^2

TEMP_HOURS = 12
HEAT_ID = 12

MAX_TIME_DELTA_FOR_RULES_SERVICE_MIN = 5

START_RULE = 1
STOP_RULE = 2
ENABLED_RULE = 1

BACKEND_IP = os.environ["BACKEND_IP"]

# Should be max+1 from max id from table
BRANCHES_LENGTH = 40
RULES_FOR_BRANCHES = [None] * BRANCHES_LENGTH
BRANCHES_SETTINGS = {}
APP_SETTINGS = {}

REDIS_KEY_FOR_UPPER_TANK = "UPPER_TANK"
REDIS_KEY_FOR_CESSTOOL = "CESSTOOL"
TANK_NOTIFICATION_MINUTES = 1
CESSTOOL_NOTIFICATION_MINUTES = 60 * 8
LINES_UPPER_TANK = {"upper_tank": LINE_UPPER_TANK, "upper_tank_sv": LINE_UPPER_TANK_AV}

########## TELEGRAM SETTINGS #############

REDIS_KEY_FOR_MESSENGER = "telegram_sent_intervals"
MESSENGER_SENT_TIMEOUT = 10
USERS = [{"name": "Cottage", "id": "-315337397"}]

# Settings for upper tanks
TELEGRAM_USERS = {
     "upper_tank": USERS,
     "cesspool": USERS,
     }