version: "3.7"
services:
    device_discovery:
        build:
            context: ./
            dockerfile: ./device_discovery/Dockerfile
        container_name: device_discovery
        environment: 
            DATABASE_URI: postgresql://$DB_USERNAME:$DB_PASSWORD@172.19.0.2:11000==(postgres):5432/smart_house
        command: ["uvicorn", "device_discovery.main:app", "--host", "0.0.0.0", "--port", "8020"]
        ports:
            - 8020:8020
        expose: 
            - 8020
        depends_on:    
            - postgres
        # restart: on-failure
    
    postgres:
        image: "postgres:13-alpine"
        container_name: postgres
        environment:
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
            PGDATA: /data/postgres
        volumes:
            - ./database/psql:/docker-entrypoint-initdb.d
            # - postgres-data:/data/postgres
        ports:
            - 5432:5432
        expose: 
            - 5432
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready --username=${DB_USERNAME} --dbname=${DB_DATABASE}"]
            interval: 10s
            timeout: 5s
            retries: 5

    postgres-admin:
        image: dpage/pgadmin4
        container_name: postgres-admin
        environment:
            PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
            PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
        ports:
            - 5433:80
        restart: unless-stopped
        
volumes:
    postgres-data:
