# version: '3.7'
# services:
#     certbot:
#         image: certbot/certbot
#         volumes:
#             - ./nginx/data/certbot/conf:/etc/letsencrypt
#             - ./nginx/data/certbot/www:/var/www/certbot
    